-- Worked example, step 3 of 4: assign and onboard from CSV, look through each role's eyes, survive
-- the pipeline team rebuilding their table, offboard. Every role's view is captured into a session
-- variable while that role is active, with secondary roles OFF, so no other role the tester holds
-- can leak access into the result.

USE ROLE RAP_DEMO_ADMIN;
USE SECONDARY ROLES NONE;
USE WAREHOUSE RAP_DEMO_WH;
SET ME = CURRENT_USER();

---------------------------------------------------------------------------------------------------
-- 1. The business assigns rows to groups. The analyst's CSV: RECORD_ID, MAPPING_KEY, ROLE_NAME.
---------------------------------------------------------------------------------------------------
COPY INTO @RAP_DEMO.GOVERNANCE.ACCESS_REQUESTS/request_01.csv FROM (
  SELECT * FROM VALUES
    ('T-1001', 'NORTH', 'RAP_DEMO_NORTH_TEAM'),
    ('T-1002', 'NORTH', 'RAP_DEMO_NORTH_TEAM'),
    ('T-1003', 'NORTH', 'RAP_DEMO_NORTH_TEAM'),
    ('T-1004', 'NORTH', 'RAP_DEMO_NORTH_TEAM'),
    ('T-2001', 'SOUTH', 'RAP_DEMO_SOUTH_TEAM'),
    ('T-2002', 'SOUTH', 'RAP_DEMO_SOUTH_TEAM'),
    ('T-2003', 'SOUTH', 'RAP_DEMO_SOUTH_TEAM'),
    ('T-3001', 'EAST',  'RAP_DEMO_SOUTH_TEAM'),
    ('T-3002', 'EAST',  'RAP_DEMO_SOUTH_TEAM'),
    ('T-3003', 'EAST',  'RAP_DEMO_EAST_TEAM')
  AS t(RECORD_ID, MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- request_02 breaks every rule once, plus one valid row (T-4002) that must NOT be applied, because
-- a file with any failure is rejected whole. T-4001 is listed under two keys.
COPY INTO @RAP_DEMO.GOVERNANCE.ACCESS_REQUESTS/request_02.csv FROM (
  SELECT * FROM VALUES
    ('T-4002', 'WEST',        'RAP_DEMO_WEST_TEAM'),
    ('T-9999', 'WEST',        'RAP_DEMO_WEST_TEAM'),
    ('T-4001', 'WEST',        'RAP_DEMO_WEST_TEAM'),
    ('T-4001', 'NORTH',       'RAP_DEMO_NORTH_TEAM'),
    ('T-1001', 'west region', 'RAP_DEMO_WEST_TEAM'),
    ('T-1002', 'WEST',        'rap_demo_west_team'),
    ('T-1003', 'WEST',        'X; DROP TABLE RAP_DEMO.SHARED.SERVICE_TICKETS')
  AS t(RECORD_ID, MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- Expect: 10 records assigned, 4 mappings, 3 roles.
CALL RAP_DEMO.GOVERNANCE.SP_ONBOARD_ACCESS('request_01.csv');
SET ONBOARD_1 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

-- Re-running the same file changes nothing.
CALL RAP_DEMO.GOVERNANCE.SP_ONBOARD_ACCESS('request_01.csv');
SET ONBOARD_RERUN = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

-- Expect: whole file rejected, 6 of 7 rows logged, nothing applied.
CALL RAP_DEMO.GOVERNANCE.SP_ONBOARD_ACCESS('request_02.csv');
SET ONBOARD_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SHOW ROLES LIKE 'RAP_DEMO_WEST_TEAM';
SET WEST_ROLE_CREATED = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
-- T-1001 keeps its key, T-4002 stays unassigned, and the unassigned count is unchanged.
SET STATE_AFTER_REJECT =
  (SELECT MAX(IFF(TICKET_ID = 'T-1001', MAPPING_KEY, NULL)) || '|' ||
          COUNT_IF(MAPPING_KEY IS NULL)
   FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

---------------------------------------------------------------------------------------------------
-- 2. Test roles, set up the way a consumer's own onboarding would: assign to a user, give compute.
--    A control role has SELECT directly but no mapping; an auditor role is exempt from the policy.
---------------------------------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS RAP_DEMO_NO_MAPPING;
CREATE ROLE IF NOT EXISTS RAP_DEMO_AUDITOR;
GRANT USAGE ON DATABASE RAP_DEMO TO ROLE RAP_DEMO_NO_MAPPING;
GRANT USAGE ON SCHEMA RAP_DEMO.SHARED TO ROLE RAP_DEMO_NO_MAPPING;
GRANT SELECT ON TABLE RAP_DEMO.SHARED.SERVICE_TICKETS TO ROLE RAP_DEMO_NO_MAPPING;
GRANT USAGE ON DATABASE RAP_DEMO TO ROLE RAP_DEMO_AUDITOR;
GRANT USAGE ON SCHEMA RAP_DEMO.SHARED TO ROLE RAP_DEMO_AUDITOR;
GRANT SELECT ON TABLE RAP_DEMO.SHARED.SERVICE_TICKETS TO ROLE RAP_DEMO_AUDITOR;
GRANT ROLE RAP_DEMO_NORTH_TEAM TO USER IDENTIFIER($ME);
GRANT ROLE RAP_DEMO_SOUTH_TEAM TO USER IDENTIFIER($ME);
GRANT ROLE RAP_DEMO_EAST_TEAM  TO USER IDENTIFIER($ME);
GRANT ROLE RAP_DEMO_NO_MAPPING TO USER IDENTIFIER($ME);
GRANT ROLE RAP_DEMO_AUDITOR    TO USER IDENTIFIER($ME);
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE RAP_DEMO_NORTH_TEAM;
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE RAP_DEMO_SOUTH_TEAM;
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE RAP_DEMO_EAST_TEAM;
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE RAP_DEMO_NO_MAPPING;
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE RAP_DEMO_AUDITOR;
GRANT USAGE ON WAREHOUSE RAP_DEMO_WH TO ROLE SYSADMIN;

---------------------------------------------------------------------------------------------------
-- 3. Look through each role's eyes.
---------------------------------------------------------------------------------------------------
SET ADMIN_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);   -- admin is exempt

USE ROLE RAP_DEMO_NORTH_TEAM;  USE SECONDARY ROLES NONE;
SET NORTH_KEYS = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
SET NORTH_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
-- A viewer cannot see, let alone change, the mapping.
EXECUTE IMMEDIATE $$
BEGIN
  INSERT INTO RAP_DEMO.GOVERNANCE.ACCESS_MAPPING (MAPPING_KEY, ROLE_NAME) VALUES ('WEST', 'RAP_DEMO_NORTH_TEAM');
  RETURN 'WROTE';
EXCEPTION
  WHEN OTHER THEN RETURN 'DENIED';
END;
$$;
SET VIEWER_WRITE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_KEYS = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
SET SOUTH_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

USE ROLE RAP_DEMO_EAST_TEAM;   USE SECONDARY ROLES NONE;
SET EAST_KEYS = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
SET EAST_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

USE ROLE RAP_DEMO_NO_MAPPING;  USE SECONDARY ROLES NONE;
SET NOMAP_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
-- Consumers are never given the pipeline team's table.
EXECUTE IMMEDIATE $$
BEGIN
  LET n INTEGER := (SELECT COUNT(*) FROM RAP_DEMO.SOURCE.SERVICE_TICKETS);
  RETURN 'READ';
EXCEPTION
  WHEN OTHER THEN RETURN 'DENIED';
END;
$$;
SET NOMAP_SOURCE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_AUDITOR;     USE SECONDARY ROLES NONE;
SET AUDITOR_ROWS = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

-- SYSADMIN inherits every viewer role (they were granted to it), so it sees all MAPPED rows.
USE ROLE SYSADMIN;             USE SECONDARY ROLES NONE;
SET SYSADMIN_KEYS = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;

---------------------------------------------------------------------------------------------------
-- 4. The pipeline team rebuilds their table. First a half-built rebuild (empty table), which the
--    refresh must refuse; then a real rebuild that adds T-1005, drops T-2003 and changes T-1001.
---------------------------------------------------------------------------------------------------
USE ROLE RAP_DEMO_PIPELINE;    USE SECONDARY ROLES NONE;
CREATE OR REPLACE TABLE RAP_DEMO.SOURCE.SERVICE_TICKETS (
  TICKET_ID VARCHAR, OPENED_ON DATE, CATEGORY VARCHAR, STATUS VARCHAR);
GRANT SELECT ON TABLE RAP_DEMO.SOURCE.SERVICE_TICKETS TO ROLE RAP_DEMO_ADMIN;

USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_DEMO.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFUSED = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SET COPY_AFTER_REFUSE = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

USE ROLE RAP_DEMO_PIPELINE;    USE SECONDARY ROLES NONE;
CREATE OR REPLACE TABLE RAP_DEMO.SOURCE.SERVICE_TICKETS (
  TICKET_ID VARCHAR, OPENED_ON DATE, CATEGORY VARCHAR, STATUS VARCHAR);
INSERT INTO RAP_DEMO.SOURCE.SERVICE_TICKETS VALUES
  ('T-1001', '2026-01-05', 'Repair',       'Reopened'),
  ('T-1002', '2026-01-08', 'Installation', 'Open'),
  ('T-1003', '2026-01-12', 'Inspection',   'Open'),
  ('T-1004', '2026-01-19', 'Repair',       'Closed'),
  ('T-1005', '2026-02-02', 'Repair',       'Open'),
  ('T-2001', '2026-01-06', 'Repair',       'Open'),
  ('T-2002', '2026-01-14', 'Inspection',   'Closed'),
  ('T-3001', '2026-01-07', 'Repair',       'Open'),
  ('T-3002', '2026-01-15', 'Repair',       'Closed'),
  ('T-3003', '2026-01-22', 'Inspection',   'Open'),
  ('T-4001', '2026-01-09', 'Installation', 'Open'),
  ('T-4002', '2026-01-16', 'Repair',       'Closed');
GRANT SELECT ON TABLE RAP_DEMO.SOURCE.SERVICE_TICKETS TO ROLE RAP_DEMO_ADMIN;

-- The rebuild touched only their table: the governed copy and its assignments are untouched.
USE ROLE RAP_DEMO_NORTH_TEAM;  USE SECONDARY ROLES NONE;
SET NORTH_ROWS_BEFORE_REFRESH = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

-- Refresh (the scheduled task runs this same call; on demand: EXECUTE TASK ...TSK_REFRESH_SERVICE_TICKETS).
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_DEMO.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFRESH_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_NORTH_TEAM;  USE SECONDARY ROLES NONE;
-- Assignments survived, the changed row carries its new data, the new row is not yet visible.
SET NORTH_ROWS_REFRESHED = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
SET NORTH_T1001 = (SELECT STATUS FROM RAP_DEMO.SHARED.SERVICE_TICKETS WHERE TICKET_ID = 'T-1001');
USE ROLE RAP_DEMO_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_ROWS_REFRESHED = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);   -- T-2003 gone

-- Soft delete: T-2003 left the source, so viewers no longer see it, but the row and its SOUTH key
-- are still in the governed copy (admin view).
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
SET REMOVED_STATE = (SELECT MAPPING_KEY || '|' || IFF(REMOVED_AT IS NOT NULL, 'removed', 'live')
                     FROM RAP_DEMO.SHARED.SERVICE_TICKETS WHERE TICKET_ID = 'T-2003');

-- The business assigns the new row.
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
COPY INTO @RAP_DEMO.GOVERNANCE.ACCESS_REQUESTS/request_03.csv FROM (
  SELECT * FROM VALUES ('T-1005', 'NORTH', 'RAP_DEMO_NORTH_TEAM')
  AS t(RECORD_ID, MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;
CALL RAP_DEMO.GOVERNANCE.SP_ONBOARD_ACCESS('request_03.csv');
SET ONBOARD_3 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_NORTH_TEAM;  USE SECONDARY ROLES NONE;
SET NORTH_ROWS_ASSIGNED = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;

---------------------------------------------------------------------------------------------------
-- 4b. The record comes back (a partial rebuild, say). It is restored with its key: no CSV needed.
---------------------------------------------------------------------------------------------------
USE ROLE RAP_DEMO_PIPELINE;    USE SECONDARY ROLES NONE;
INSERT INTO RAP_DEMO.SOURCE.SERVICE_TICKETS VALUES ('T-2003', '2026-01-21', 'Installation', 'Open');

USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_DEMO.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFRESH_3 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_ROWS_RESTORED = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;

---------------------------------------------------------------------------------------------------
-- 5. Offboarding. Access ends on the next query; data is never deleted.
---------------------------------------------------------------------------------------------------
COPY INTO @RAP_DEMO.GOVERNANCE.ACCESS_REQUESTS/offboard_01.csv FROM (
  SELECT * FROM VALUES ('EAST', 'RAP_DEMO_SOUTH_TEAM') AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- offboard_02: one real mapping, one that never existed. Rejected whole.
COPY INTO @RAP_DEMO.GOVERNANCE.ACCESS_REQUESTS/offboard_02.csv FROM (
  SELECT * FROM VALUES
    ('EAST', 'RAP_DEMO_EAST_TEAM'),
    ('WEST', 'RAP_DEMO_WEST_TEAM')
  AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

CALL RAP_DEMO.GOVERNANCE.SP_OFFBOARD_ACCESS_FILE('offboard_01.csv', FALSE);
SET OFFBOARD_1 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
CALL RAP_DEMO.GOVERNANCE.SP_OFFBOARD_ACCESS_FILE('offboard_02.csv', FALSE);
SET OFFBOARD_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_DEMO_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_KEYS_AFTER = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);
USE ROLE RAP_DEMO_EAST_TEAM;   USE SECONDARY ROLES NONE;
SET EAST_KEYS_AFTER = (SELECT LISTAGG(DISTINCT MAPPING_KEY, ',') WITHIN GROUP (ORDER BY MAPPING_KEY) FROM RAP_DEMO.SHARED.SERVICE_TICKETS);

-- Single-mapping call, dropping the north role: it maps to nothing afterwards.
USE ROLE RAP_DEMO_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_DEMO.GOVERNANCE.SP_OFFBOARD_ACCESS('NORTH', 'RAP_DEMO_NORTH_TEAM', TRUE);
SET OFFBOARD_SINGLE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SHOW ROLES LIKE 'RAP_DEMO_NORTH_TEAM';
SET NORTH_ROLE_LEFT = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
-- The north rows are still in the table, just visible to no role.
SET NORTH_ROWS_KEPT = (SELECT COUNT(*) FROM RAP_DEMO.SHARED.SERVICE_TICKETS WHERE MAPPING_KEY = 'NORTH');
