--------------------------------------------------------------------------------
-- 01_setup.sql
-- RAM V2 Example: database, schemas, roles, invented source data, grants
-- Run as ACCOUNTADMIN
--------------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

-- Database
CREATE OR REPLACE DATABASE RAM_V2_EXAMPLE;

-- Schemas
CREATE SCHEMA RAM_V2_EXAMPLE.SOURCE;
CREATE SCHEMA RAM_V2_EXAMPLE.SHARED;
CREATE SCHEMA RAM_V2_EXAMPLE.GOVERNANCE;

-- Admin role
CREATE ROLE IF NOT EXISTS RAM_V2_ADMIN;
GRANT ROLE RAM_V2_ADMIN TO ROLE ACCOUNTADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE RAM_V2_ADMIN;

-- Database / schema grants to admin
GRANT USAGE ON DATABASE RAM_V2_EXAMPLE TO ROLE RAM_V2_ADMIN WITH GRANT OPTION;
GRANT USAGE ON SCHEMA RAM_V2_EXAMPLE.SOURCE TO ROLE RAM_V2_ADMIN;
GRANT OWNERSHIP ON SCHEMA RAM_V2_EXAMPLE.SHARED TO ROLE RAM_V2_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RAM_V2_EXAMPLE.GOVERNANCE TO ROLE RAM_V2_ADMIN COPY CURRENT GRANTS;

-- Source table (owned by ACCOUNTADMIN, simulating the source team)
CREATE OR REPLACE TABLE RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS (
    MOVEMENT_ID   INTEGER      NOT NULL,
    PRODUCT_ID    VARCHAR(20)  NOT NULL,
    SUPPLIER_ID   VARCHAR(20)  NOT NULL,
    WAREHOUSE_CODE VARCHAR(10) NOT NULL,
    QUANTITY      INTEGER      NOT NULL,
    MOVEMENT_TYPE VARCHAR(10)  NOT NULL,
    MOVEMENT_DATE DATE         NOT NULL,
    PRIMARY KEY (MOVEMENT_ID)
);

-- Insert ~2000 rows: 50 product/supplier pairs x 40 rows each
INSERT INTO RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS
WITH pairs AS (
    SELECT
        'P' || (1001 + p.idx)::VARCHAR AS PRODUCT_ID,
        'S' || (2001 + s.idx)::VARCHAR AS SUPPLIER_ID
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS idx
          FROM TABLE(GENERATOR(ROWCOUNT => 10))) p
    CROSS JOIN
         (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS idx
          FROM TABLE(GENERATOR(ROWCOUNT => 5))) s
)
SELECT
    ROW_NUMBER() OVER (ORDER BY p.PRODUCT_ID, p.SUPPLIER_ID, r.idx) AS MOVEMENT_ID,
    p.PRODUCT_ID,
    p.SUPPLIER_ID,
    'WH-' || (MOD(r.idx, 3) + 1)::VARCHAR                          AS WAREHOUSE_CODE,
    (MOD(ABS(HASH(p.PRODUCT_ID || p.SUPPLIER_ID || r.idx::VARCHAR)), 500) + 1)::INTEGER AS QUANTITY,
    CASE MOD(r.idx, 3) WHEN 0 THEN 'IN' WHEN 1 THEN 'OUT' ELSE 'TRANSFER' END AS MOVEMENT_TYPE,
    DATEADD('day', -MOD(r.idx, 365), CURRENT_DATE())                AS MOVEMENT_DATE
FROM pairs p
CROSS JOIN (SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS idx
            FROM TABLE(GENERATOR(ROWCOUNT => 40))) r;

-- Grant source read to admin
GRANT SELECT ON TABLE RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS TO ROLE RAM_V2_ADMIN;

-- Confirm
SELECT 'SOURCE ROW COUNT' AS CHECK_LABEL,
       COUNT(*)           AS ROW_COUNT
FROM RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS;
