--------------------------------------------------------------------------------
-- 02_objects.sql
-- RAM V2 Example: governed copy, policy, lifecycle tables, mutex, procedures, task
-- Run as RAM_V2_ADMIN (owns SHARED and GOVERNANCE schemas)
--------------------------------------------------------------------------------
USE ROLE RAM_V2_ADMIN;
USE DATABASE RAM_V2_EXAMPLE;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================
-- A. GOVERNED COPY (SHARED schema)
-- ============================================================
CREATE OR REPLACE TABLE SHARED.GOVERNED_STOCK_MOVEMENTS (
    MOVEMENT_ID    INTEGER      NOT NULL,
    PRODUCT_ID     VARCHAR(20)  NOT NULL,
    SUPPLIER_ID    VARCHAR(20)  NOT NULL,
    WAREHOUSE_CODE VARCHAR(10),
    QUANTITY       INTEGER,
    MOVEMENT_TYPE  VARCHAR(10),
    MOVEMENT_DATE  DATE,
    MAPPING_KEY    VARCHAR(100),
    REMOVED_AT     TIMESTAMP_NTZ,
    REFRESHED_AT   TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (MOVEMENT_ID)
);

-- ============================================================
-- B. GOVERNANCE TABLES
-- ============================================================

-- Access mappings: which key maps to which role
CREATE OR REPLACE TABLE GOVERNANCE.ACCESS_MAPPING (
    MAPPING_KEY VARCHAR(100)  NOT NULL,
    ROLE_NAME   VARCHAR(256)  NOT NULL,
    CREATED_AT  TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (MAPPING_KEY, ROLE_NAME)
);

-- Durable pair assignments (business-grain, survives refresh)
CREATE OR REPLACE TABLE GOVERNANCE.PAIR_ASSIGNMENTS (
    PRODUCT_ID       VARCHAR(20)  NOT NULL,
    SUPPLIER_ID      VARCHAR(20)  NOT NULL,
    MAPPING_KEY      VARCHAR(100) NOT NULL,
    ASSIGNED_AT      TIMESTAMP_NTZ NOT NULL,
    ASSIGNED_BY_RUN_ID INTEGER    NOT NULL,
    PRIMARY KEY (PRODUCT_ID, SUPPLIER_ID)
);

-- Key registry with blocked flag and generation
CREATE OR REPLACE TABLE GOVERNANCE.V2_KEYS (
    MAPPING_KEY VARCHAR(100)  NOT NULL PRIMARY KEY,
    BLOCKED     BOOLEAN       NOT NULL DEFAULT FALSE,
    GENERATION  INTEGER       NOT NULL DEFAULT 1,
    CREATED_AT  TIMESTAMP_NTZ NOT NULL,
    UPDATED_AT  TIMESTAMP_NTZ NOT NULL
);

-- Run log
-- Run IDs come from an explicitly ORDERed sequence and are taken BEFORE the insert. New AUTOINCREMENT
-- columns default to NOORDER (Snowflake behaviour change 2024_01), so MAX(RUN_ID) after an insert
-- is not guaranteed to be the row just inserted.
CREATE OR REPLACE SEQUENCE GOVERNANCE.RUN_ID_SEQ START = 1 INCREMENT = 1 ORDER;
CREATE OR REPLACE TABLE GOVERNANCE.V2_RUNS (
    RUN_ID     INTEGER NOT NULL,
    OPERATION  VARCHAR(20)  NOT NULL,
    FILENAME   VARCHAR(256),
    STARTED_AT TIMESTAMP_NTZ NOT NULL,
    COMPLETED_AT TIMESTAMP_NTZ,
    STATUS     VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    RESULT_SUMMARY VARIANT,
    ACTOR      VARCHAR(256) NOT NULL,
    PRIMARY KEY (RUN_ID)
);

-- Logical requests (one per unique pair+key)
CREATE OR REPLACE TABLE GOVERNANCE.V2_REQUESTS (
    REQUEST_ID INTEGER AUTOINCREMENT ORDER NOT NULL,
    RUN_ID     INTEGER      NOT NULL,
    PRODUCT_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    MAPPING_KEY VARCHAR(100),
    ROLE_NAME  VARCHAR(256),
    STATUS     VARCHAR(20)  NOT NULL,
    REASON     VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    RESOLVED_AT TIMESTAMP_NTZ,
    RESOLVED_BY_RUN_ID INTEGER,
    PRIMARY KEY (REQUEST_ID)
);

-- Submission observations (one per physical CSV row)
CREATE OR REPLACE TABLE GOVERNANCE.V2_SUBMISSIONS (
    SUBMISSION_ID INTEGER AUTOINCREMENT ORDER NOT NULL,
    RUN_ID     INTEGER      NOT NULL,
    FILENAME   VARCHAR(256) NOT NULL,
    FILE_ROW_NUM INTEGER    NOT NULL,
    RAW_LINE   VARCHAR(2000),
    PRODUCT_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    MAPPING_KEY VARCHAR(100),
    REQUEST_ID INTEGER,
    OUTCOME    VARCHAR(20)  NOT NULL,
    REASON     VARCHAR(1000),
    SUBMITTED_AT TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (SUBMISSION_ID)
);

-- Audit log
CREATE OR REPLACE TABLE GOVERNANCE.AUDIT_LOG (
    AUDIT_ID  INTEGER AUTOINCREMENT ORDER NOT NULL,
    RUN_ID    INTEGER,
    OPERATION VARCHAR(30) NOT NULL,
    DETAIL    VARIANT,
    ACTOR     VARCHAR(256) NOT NULL,
    LOGGED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (AUDIT_ID)
);

-- Single-writer mutex
CREATE OR REPLACE TABLE GOVERNANCE.V2_MUTEX (
    LOCK_KEY        VARCHAR(1)    NOT NULL DEFAULT 'X',
    TOKEN           VARCHAR(50)   NOT NULL,
    OWNER_SESSION   VARCHAR(100)  NOT NULL,
    ACQUIRED_AT     TIMESTAMP_NTZ NOT NULL,
    PRIMARY KEY (LOCK_KEY)
);

-- Configuration
CREATE OR REPLACE TABLE GOVERNANCE.CONFIG (
    CONFIG_KEY   VARCHAR(50) NOT NULL PRIMARY KEY,
    CONFIG_VALUE VARCHAR(200)
);
INSERT INTO GOVERNANCE.CONFIG VALUES ('ROLE_PREFIX', 'RAM_V2_');
INSERT INTO GOVERNANCE.CONFIG VALUES ('ROLE_SUFFIX', '_VIEWER');
INSERT INTO GOVERNANCE.CONFIG VALUES ('PENDING_RECHECK', 'YES');
INSERT INTO GOVERNANCE.CONFIG VALUES ('OFFBOARD_DROP_ROLE', 'NO');

-- ============================================================
-- C. STAGE AND FILE FORMAT
-- ============================================================
CREATE OR REPLACE STAGE GOVERNANCE.REQUEST_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE FILE FORMAT GOVERNANCE.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    NULL_IF = ();

-- ============================================================
-- D. ROW ACCESS POLICY
-- ============================================================
CREATE OR REPLACE ROW ACCESS POLICY SHARED.ROW_ACCESS_FILTER
AS (row_key VARCHAR, row_removed_at TIMESTAMP_NTZ)
RETURNS BOOLEAN ->
    IS_ROLE_IN_SESSION('RAM_V2_ADMIN')
    OR (
        row_removed_at IS NULL
        AND EXISTS (
            SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING m
            WHERE m.MAPPING_KEY = row_key
              AND IS_ROLE_IN_SESSION(m.ROLE_NAME)
        )
    );

ALTER TABLE SHARED.GOVERNED_STOCK_MOVEMENTS
    ADD ROW ACCESS POLICY SHARED.ROW_ACCESS_FILTER
    ON (MAPPING_KEY, REMOVED_AT);

-- ============================================================
-- E. PROCEDURES
-- ============================================================

-- E1. REFRESH GOVERNED COPY ------------------------------------------------
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_REFRESH_GOVERNED_COPY()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    v_token   VARCHAR DEFAULT UUID_STRING();
    v_now     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_actor   VARCHAR DEFAULT CURRENT_USER();
    v_run_id  INTEGER;
    v_snap    INTEGER;
    v_dups    INTEGER;
BEGIN
    -- Acquire mutex
    BEGIN
        INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX (LOCK_KEY, TOKEN, OWNER_SESSION, ACQUIRED_AT)
            VALUES ('X', :v_token, CURRENT_SESSION()::VARCHAR, :v_now);
    EXCEPTION WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Mutex held by another writer');
    END;

    -- Create run
    SELECT RAM_V2_EXAMPLE.GOVERNANCE.RUN_ID_SEQ.NEXTVAL INTO :v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS (RUN_ID, OPERATION, STARTED_AT, STATUS, ACTOR)
        VALUES (:v_run_id, 'REFRESH', :v_now, 'RUNNING', :v_actor);

    -- Snapshot source
    CREATE OR REPLACE TEMPORARY TABLE t_refresh_snap AS
        SELECT * FROM RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS;
    SELECT COUNT(*) INTO :v_snap FROM t_refresh_snap;
    IF (:v_snap = 0) THEN
        UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS
            SET STATUS='FAILED', COMPLETED_AT=:v_now,
                RESULT_SUMMARY=OBJECT_CONSTRUCT('reason','Empty source')
            WHERE RUN_ID=:v_run_id;
        DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Empty source');
    END IF;

    -- Verify unique merge key
    SELECT COUNT(*) INTO :v_dups FROM (
        SELECT MOVEMENT_ID FROM t_refresh_snap GROUP BY MOVEMENT_ID HAVING COUNT(*)>1);
    IF (:v_dups > 0) THEN
        UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS
            SET STATUS='FAILED', COMPLETED_AT=:v_now,
                RESULT_SUMMARY=OBJECT_CONSTRUCT('reason','Duplicate MOVEMENT_ID')
            WHERE RUN_ID=:v_run_id;
        DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Duplicate MOVEMENT_ID');
    END IF;

    -- Soft-delete rows absent from source
    UPDATE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS
        SET REMOVED_AT = COALESCE(REMOVED_AT, :v_now), REFRESHED_AT = :v_now
        WHERE MOVEMENT_ID NOT IN (SELECT MOVEMENT_ID FROM t_refresh_snap);

    -- Merge: update/insert, apply MAPPING_KEY from durable pair assignments
    MERGE INTO RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS t
    USING (
        SELECT s.MOVEMENT_ID, s.PRODUCT_ID, s.SUPPLIER_ID, s.WAREHOUSE_CODE,
               s.QUANTITY, s.MOVEMENT_TYPE, s.MOVEMENT_DATE,
               a.MAPPING_KEY
        FROM t_refresh_snap s
        LEFT JOIN RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
            ON s.PRODUCT_ID = a.PRODUCT_ID AND s.SUPPLIER_ID = a.SUPPLIER_ID
    ) src ON t.MOVEMENT_ID = src.MOVEMENT_ID
    WHEN MATCHED THEN UPDATE SET
        t.PRODUCT_ID     = src.PRODUCT_ID,
        t.SUPPLIER_ID    = src.SUPPLIER_ID,
        t.WAREHOUSE_CODE = src.WAREHOUSE_CODE,
        t.QUANTITY        = src.QUANTITY,
        t.MOVEMENT_TYPE   = src.MOVEMENT_TYPE,
        t.MOVEMENT_DATE   = src.MOVEMENT_DATE,
        t.MAPPING_KEY     = src.MAPPING_KEY,
        t.REMOVED_AT      = NULL,
        t.REFRESHED_AT    = :v_now
    WHEN NOT MATCHED THEN INSERT
        (MOVEMENT_ID,PRODUCT_ID,SUPPLIER_ID,WAREHOUSE_CODE,QUANTITY,MOVEMENT_TYPE,MOVEMENT_DATE,MAPPING_KEY,REMOVED_AT,REFRESHED_AT)
        VALUES
        (src.MOVEMENT_ID,src.PRODUCT_ID,src.SUPPLIER_ID,src.WAREHOUSE_CODE,src.QUANTITY,src.MOVEMENT_TYPE,src.MOVEMENT_DATE,src.MAPPING_KEY,NULL,:v_now);

    -- Complete
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS
        SET STATUS='COMPLETED', COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
            RESULT_SUMMARY=OBJECT_CONSTRUCT('snapshot_rows',:v_snap)
        WHERE RUN_ID=:v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG (RUN_ID,OPERATION,DETAIL,ACTOR)
        SELECT :v_run_id,'REFRESH',OBJECT_CONSTRUCT('snapshot_rows',:v_snap),:v_actor;
    DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;
    RETURN OBJECT_CONSTRUCT('STATUS','COMPLETED','RUN_ID',:v_run_id,'SNAPSHOT_ROWS',:v_snap);

EXCEPTION WHEN OTHER THEN
    BEGIN ROLLBACK; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ WHERE RUN_ID=:v_run_id; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token; EXCEPTION WHEN OTHER THEN NULL; END;
    RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON',SQLERRM,'ERROR_CODE',SQLCODE);
END;

-- E2. ONBOARD ACCESS V2 ---------------------------------------------------
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_ONBOARD_ACCESS_V2(P_FILE VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    v_ddl     VARCHAR;
    v_mk      VARCHAR;
    v_token   VARCHAR DEFAULT UUID_STRING();
    v_now     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_actor   VARCHAR DEFAULT CURRENT_USER();
    v_run_id  INTEGER;
    v_safe    VARCHAR;
    v_sql     VARCHAR;
    v_cnt_pass     INTEGER DEFAULT 0;
    v_cnt_pending  INTEGER DEFAULT 0;
    v_cnt_rejected INTEGER DEFAULT 0;
    v_cnt_skipped  INTEGER DEFAULT 0;
    v_cnt_dup      INTEGER DEFAULT 0;
    v_cnt_recheck  INTEGER DEFAULT 0;
    v_prefix  VARCHAR;
    v_suffix  VARCHAR;
BEGIN
    -- Read config
    SELECT CONFIG_VALUE INTO :v_prefix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_PREFIX';
    SELECT CONFIG_VALUE INTO :v_suffix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_SUFFIX';

    -- Validate filename
    IF (P_FILE IS NULL OR LENGTH(TRIM(P_FILE)) = 0) THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Empty filename');
    END IF;
    v_safe := TRIM(P_FILE);
    IF (NOT REGEXP_LIKE(:v_safe, '^[A-Za-z0-9_-]+\\.csv$')) THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Invalid filename format');
    END IF;

    -- Acquire mutex
    BEGIN
        INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX (LOCK_KEY,TOKEN,OWNER_SESSION,ACQUIRED_AT)
            VALUES ('X',:v_token,CURRENT_SESSION()::VARCHAR,:v_now);
    EXCEPTION WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Mutex held by another writer');
    END;

    -- Create run
    SELECT RAM_V2_EXAMPLE.GOVERNANCE.RUN_ID_SEQ.NEXTVAL INTO :v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS (RUN_ID, OPERATION,FILENAME,STARTED_AT,STATUS,ACTOR)
        VALUES (:v_run_id, 'ONBOARD',:v_safe,:v_now,'RUNNING',:v_actor);

    -- Read CSV from stage into temp table (all rows including header)
    v_sql := 'CREATE OR REPLACE TEMPORARY TABLE t_csv_raw AS '
        || 'SELECT METADATA$FILE_ROW_NUMBER AS FILE_ROW, '
        || '$1 AS COL1, $2 AS COL2, $3 AS COL3, $4 AS COL4 '
        || 'FROM @RAM_V2_EXAMPLE.GOVERNANCE.REQUEST_STAGE/' || :v_safe
        || ' (FILE_FORMAT => ''RAM_V2_EXAMPLE.GOVERNANCE.CSV_FORMAT'')';
    BEGIN
        EXECUTE IMMEDIATE :v_sql;
    EXCEPTION WHEN OTHER THEN
        UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
            RESULT_SUMMARY=OBJECT_CONSTRUCT('reason','Cannot read file: '||SQLERRM) WHERE RUN_ID=:v_run_id;
        DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Cannot read file: '||SQLERRM);
    END;

    -- A missing file reads as zero rows, not an error, so fail it explicitly
    SELECT COUNT(*) INTO :v_cnt_pass FROM t_csv_raw;
    IF (:v_cnt_pass = 0) THEN
        UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
            RESULT_SUMMARY=OBJECT_CONSTRUCT('reason','File not found on stage or empty') WHERE RUN_ID=:v_run_id;
        DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','File not found on stage or empty','RUN_ID',:v_run_id);
    END IF;

    -- Build working table (skip header row 1)
    CREATE OR REPLACE TEMPORARY TABLE t_work AS
    SELECT
        ROW_NUMBER() OVER (ORDER BY FILE_ROW) AS ROW_NUM,
        FILE_ROW,
        COL1 || ',' || COL2 || ',' || COALESCE(COL3,'') AS RAW_LINE,
        TRIM(COL1)  AS PRODUCT_ID,
        TRIM(COL2)  AS SUPPLIER_ID,
        TRIM(COL3)  AS MAPPING_KEY,
        COL4         AS EXTRA_COL,
        :v_prefix || TRIM(COL3) || :v_suffix AS DERIVED_ROLE,
        'VALID'::VARCHAR(20)  AS STATUS,
        NULL::VARCHAR(1000)   AS REASON
    FROM t_csv_raw
    WHERE FILE_ROW > 1;

    -- Step 1: reject malformed rows
    UPDATE t_work SET STATUS='REJECTED', REASON='Extra columns detected'
        WHERE STATUS='VALID' AND EXTRA_COL IS NOT NULL AND TRIM(EXTRA_COL) != '';
    UPDATE t_work SET STATUS='REJECTED', REASON='Missing PRODUCT_ID'
        WHERE STATUS='VALID' AND (PRODUCT_ID IS NULL OR PRODUCT_ID='');
    UPDATE t_work SET STATUS='REJECTED', REASON='Missing SUPPLIER_ID'
        WHERE STATUS='VALID' AND (SUPPLIER_ID IS NULL OR SUPPLIER_ID='');
    UPDATE t_work SET STATUS='REJECTED', REASON='Missing MAPPING_KEY'
        WHERE STATUS='VALID' AND (MAPPING_KEY IS NULL OR MAPPING_KEY='');
    UPDATE t_work SET STATUS='REJECTED', REASON='Invalid MAPPING_KEY format'
        WHERE STATUS='VALID' AND NOT REGEXP_LIKE(MAPPING_KEY, '^[A-Za-z0-9_]+$');
    UPDATE t_work SET STATUS='REJECTED', REASON='Derived role name too long'
        WHERE STATUS='VALID' AND LENGTH(DERIVED_ROLE) > 256;
    UPDATE t_work SET STATUS='REJECTED', REASON='Mixed blank/nonblank identifiers'
        WHERE STATUS='VALID'
          AND ((PRODUCT_ID IS NULL OR PRODUCT_ID='') != (SUPPLIER_ID IS NULL OR SUPPLIER_ID=''));

    -- Step 2: reject conflicting keys for same pair within file
    UPDATE t_work SET STATUS='REJECTED', REASON='Conflicting key for same pair in file'
        WHERE STATUS='VALID'
          AND PRODUCT_ID || '|' || SUPPLIER_ID IN (
              SELECT PRODUCT_ID || '|' || SUPPLIER_ID FROM t_work
              WHERE STATUS='VALID' GROUP BY PRODUCT_ID, SUPPLIER_ID
              HAVING COUNT(DISTINCT MAPPING_KEY) > 1);

    -- Step 3: within-file duplicates (keep lowest ROW_NUM)
    UPDATE t_work SET STATUS='DUPLICATE', REASON='Duplicate within file'
        WHERE STATUS='VALID'
          AND ROW_NUM NOT IN (SELECT MIN(ROW_NUM) FROM t_work WHERE STATUS='VALID'
                              GROUP BY PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY);

    -- Step 4: history dedup (existing PASS or PENDING request with same pair+key)
    UPDATE t_work SET STATUS='SKIPPED', REASON='Existing active request'
        WHERE STATUS='VALID'
          AND PRODUCT_ID || '|' || SUPPLIER_ID || '|' || MAPPING_KEY IN (
              SELECT PRODUCT_ID || '|' || SUPPLIER_ID || '|' || MAPPING_KEY
              FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS WHERE STATUS IN ('PASS','PENDING'));

    -- Step 5: blocked key
    UPDATE t_work SET STATUS='REJECTED', REASON='Key is blocked (offboarded)'
        WHERE STATUS='VALID'
          AND MAPPING_KEY IN (SELECT MAPPING_KEY FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS WHERE BLOCKED=TRUE);

    -- Step 6: existing assignment with different key
    UPDATE t_work SET STATUS='REJECTED', REASON='Pair already assigned to different key'
        WHERE STATUS='VALID'
          AND PRODUCT_ID || '|' || SUPPLIER_ID IN (
              SELECT PRODUCT_ID || '|' || SUPPLIER_ID FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS)
          AND PRODUCT_ID || '|' || SUPPLIER_ID || '|' || MAPPING_KEY NOT IN (
              SELECT PRODUCT_ID || '|' || SUPPLIER_ID || '|' || MAPPING_KEY FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS
              WHERE PRODUCT_ID IS NOT NULL AND SUPPLIER_ID IS NOT NULL AND MAPPING_KEY IS NOT NULL);

    -- Step 7: check pair existence in governed copy; missing pairs are PENDING
    UPDATE t_work SET STATUS='PENDING', REASON='Pair not yet in governed data'
        WHERE STATUS='VALID'
          AND PRODUCT_ID || '|' || SUPPLIER_ID NOT IN (
              SELECT PRODUCT_ID || '|' || SUPPLIER_ID FROM RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS
              WHERE REMOVED_AT IS NULL AND PRODUCT_ID IS NOT NULL AND SUPPLIER_ID IS NOT NULL);

    -- Remaining VALID rows will become PASS after provisioning

    -- ---- DDL PHASE (outside transaction) ----
    -- Provision roles for VALID rows (will become PASS)
    LET c_roles CURSOR FOR
        SELECT DISTINCT MAPPING_KEY, DERIVED_ROLE FROM t_work WHERE STATUS='VALID';
    FOR rec IN c_roles DO
        -- Ensure key record
        v_mk := rec.MAPPING_KEY;
        MERGE INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS k
        USING (SELECT :v_mk AS mk) s ON k.MAPPING_KEY=s.mk
        WHEN NOT MATCHED THEN INSERT (MAPPING_KEY,BLOCKED,GENERATION,CREATED_AT,UPDATED_AT)
            VALUES (s.mk, FALSE, 1, :v_now, :v_now);
        -- Create role
        v_ddl := 'CREATE ROLE IF NOT EXISTS "' || rec.DERIVED_ROLE || '"';
        EXECUTE IMMEDIATE :v_ddl;
        v_ddl := 'GRANT ROLE "' || rec.DERIVED_ROLE || '" TO ROLE RAM_V2_ADMIN';
        EXECUTE IMMEDIATE :v_ddl;
        v_ddl := 'GRANT USAGE ON DATABASE RAM_V2_EXAMPLE TO ROLE "' || rec.DERIVED_ROLE || '"';
        EXECUTE IMMEDIATE :v_ddl;
        v_ddl := 'GRANT USAGE ON SCHEMA RAM_V2_EXAMPLE.SHARED TO ROLE "' || rec.DERIVED_ROLE || '"';
        EXECUTE IMMEDIATE :v_ddl;
        v_ddl := 'GRANT SELECT ON TABLE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS TO ROLE "' || rec.DERIVED_ROLE || '"';
        EXECUTE IMMEDIATE :v_ddl;
    END FOR;

    -- Also provision roles for PENDING rows (role created now, mapping later)
    LET c_proles CURSOR FOR
        SELECT DISTINCT MAPPING_KEY, DERIVED_ROLE FROM t_work WHERE STATUS='PENDING';
    FOR rec IN c_proles DO
        v_mk := rec.MAPPING_KEY;
        MERGE INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS k
        USING (SELECT :v_mk AS mk) s ON k.MAPPING_KEY=s.mk
        WHEN NOT MATCHED THEN INSERT (MAPPING_KEY,BLOCKED,GENERATION,CREATED_AT,UPDATED_AT)
            VALUES (s.mk, FALSE, 1, :v_now, :v_now);
        v_ddl := 'CREATE ROLE IF NOT EXISTS "' || rec.DERIVED_ROLE || '"';
        EXECUTE IMMEDIATE :v_ddl;
        v_ddl := 'GRANT ROLE "' || rec.DERIVED_ROLE || '" TO ROLE RAM_V2_ADMIN';
        EXECUTE IMMEDIATE :v_ddl;
    END FOR;

    -- ---- DML PHASE (atomic transaction) ----
    BEGIN TRANSACTION;

    -- Pair assignments for VALID rows
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS
        (PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY, ASSIGNED_AT, ASSIGNED_BY_RUN_ID)
    SELECT w.PRODUCT_ID, w.SUPPLIER_ID, w.MAPPING_KEY, :v_now, :v_run_id
    FROM t_work w
    WHERE w.STATUS='VALID'
      AND NOT EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
                      WHERE a.PRODUCT_ID=w.PRODUCT_ID AND a.SUPPLIER_ID=w.SUPPLIER_ID);

    -- Access mappings for VALID rows
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING (MAPPING_KEY, ROLE_NAME, CREATED_AT)
    SELECT DISTINCT w.MAPPING_KEY, w.DERIVED_ROLE, :v_now
    FROM t_work w
    WHERE w.STATUS='VALID'
      AND NOT EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING m
                      WHERE m.MAPPING_KEY=w.MAPPING_KEY AND m.ROLE_NAME=w.DERIVED_ROLE);

    -- Mark VALID as PASS
    UPDATE t_work SET STATUS='PASS' WHERE STATUS='VALID';

    -- Insert requests (one per unique logical request: PASS, PENDING, REJECTED)
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS
        (RUN_ID, PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY, ROLE_NAME, STATUS, REASON, CREATED_AT, RESOLVED_AT, RESOLVED_BY_RUN_ID)
    SELECT :v_run_id, w.PRODUCT_ID, w.SUPPLIER_ID, w.MAPPING_KEY, w.DERIVED_ROLE, w.STATUS, w.REASON, :v_now,
        CASE WHEN w.STATUS IN ('PASS','REJECTED') THEN :v_now END,
        CASE WHEN w.STATUS IN ('PASS','REJECTED') THEN :v_run_id END
    FROM t_work w
    WHERE w.STATUS NOT IN ('DUPLICATE','SKIPPED');

    -- Insert all submissions (one per physical CSV row)
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_SUBMISSIONS
        (RUN_ID, FILENAME, FILE_ROW_NUM, RAW_LINE, PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY, OUTCOME, REASON, SUBMITTED_AT)
    SELECT :v_run_id, :v_safe, w.FILE_ROW, w.RAW_LINE, w.PRODUCT_ID, w.SUPPLIER_ID, w.MAPPING_KEY,
        w.STATUS, w.REASON, :v_now
    FROM t_work w;

    COMMIT;

    -- ---- PENDING RECHECK ----
    LET v_do_recheck VARCHAR;
    SELECT CONFIG_VALUE INTO :v_do_recheck FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='PENDING_RECHECK';
    IF (:v_do_recheck = 'YES') THEN
        -- Find pending requests from earlier runs that can now resolve
        CREATE OR REPLACE TEMPORARY TABLE t_recheck AS
        SELECT r.REQUEST_ID, r.PRODUCT_ID, r.SUPPLIER_ID, r.MAPPING_KEY, r.ROLE_NAME
        FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS r
        WHERE r.STATUS = 'PENDING'
          AND r.RUN_ID != :v_run_id
          AND NOT EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS k
                          WHERE k.MAPPING_KEY=r.MAPPING_KEY AND k.BLOCKED=TRUE)
          AND EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS g
                      WHERE g.PRODUCT_ID=r.PRODUCT_ID AND g.SUPPLIER_ID=r.SUPPLIER_ID
                        AND g.REMOVED_AT IS NULL);

        SELECT COUNT(*) INTO :v_cnt_recheck FROM t_recheck;

        IF (:v_cnt_recheck > 0) THEN
            -- DDL: provision roles/grants for resolved pending
            LET c_rr CURSOR FOR SELECT DISTINCT MAPPING_KEY, ROLE_NAME FROM t_recheck;
            FOR rec IN c_rr DO
                v_ddl := 'CREATE ROLE IF NOT EXISTS "' || rec.ROLE_NAME || '"';
                EXECUTE IMMEDIATE :v_ddl;
                v_ddl := 'GRANT ROLE "' || rec.ROLE_NAME || '" TO ROLE RAM_V2_ADMIN';
                EXECUTE IMMEDIATE :v_ddl;
                v_ddl := 'GRANT USAGE ON DATABASE RAM_V2_EXAMPLE TO ROLE "' || rec.ROLE_NAME || '"';
                EXECUTE IMMEDIATE :v_ddl;
                v_ddl := 'GRANT USAGE ON SCHEMA RAM_V2_EXAMPLE.SHARED TO ROLE "' || rec.ROLE_NAME || '"';
                EXECUTE IMMEDIATE :v_ddl;
                v_ddl := 'GRANT SELECT ON TABLE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS TO ROLE "' || rec.ROLE_NAME || '"';
                EXECUTE IMMEDIATE :v_ddl;
            END FOR;

            -- DML: assignments and mappings for resolved pending
            BEGIN TRANSACTION;

            INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS
                (PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY, ASSIGNED_AT, ASSIGNED_BY_RUN_ID)
            SELECT rc.PRODUCT_ID, rc.SUPPLIER_ID, rc.MAPPING_KEY, :v_now, :v_run_id
            FROM t_recheck rc
            WHERE NOT EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
                              WHERE a.PRODUCT_ID=rc.PRODUCT_ID AND a.SUPPLIER_ID=rc.SUPPLIER_ID);

            INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING (MAPPING_KEY, ROLE_NAME, CREATED_AT)
            SELECT DISTINCT rc.MAPPING_KEY, rc.ROLE_NAME, :v_now
            FROM t_recheck rc
            WHERE NOT EXISTS (SELECT 1 FROM RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING m
                              WHERE m.MAPPING_KEY=rc.MAPPING_KEY AND m.ROLE_NAME=rc.ROLE_NAME);

            UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS r
                SET STATUS='PASS', RESOLVED_AT=:v_now, RESOLVED_BY_RUN_ID=:v_run_id
                WHERE REQUEST_ID IN (SELECT REQUEST_ID FROM t_recheck);

            INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG (RUN_ID,OPERATION,DETAIL,ACTOR)
                SELECT :v_run_id,'PENDING_RECHECK',
                    OBJECT_CONSTRUCT('resolved_count',:v_cnt_recheck),:v_actor;

            COMMIT;
        END IF;
    END IF;

    -- Apply new pair assignments to the governed copy (update MAPPING_KEY)
    UPDATE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS g
        SET MAPPING_KEY = a.MAPPING_KEY
    FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
    WHERE g.PRODUCT_ID = a.PRODUCT_ID AND g.SUPPLIER_ID = a.SUPPLIER_ID
      AND (g.MAPPING_KEY IS NULL OR g.MAPPING_KEY != a.MAPPING_KEY);

    -- Counts
    SELECT COUNT(*) INTO :v_cnt_pass     FROM t_work WHERE STATUS='PASS';
    SELECT COUNT(*) INTO :v_cnt_pending  FROM t_work WHERE STATUS='PENDING';
    SELECT COUNT(*) INTO :v_cnt_rejected FROM t_work WHERE STATUS='REJECTED';
    SELECT COUNT(*) INTO :v_cnt_skipped  FROM t_work WHERE STATUS='SKIPPED';
    SELECT COUNT(*) INTO :v_cnt_dup      FROM t_work WHERE STATUS='DUPLICATE';

    LET v_summary VARIANT := OBJECT_CONSTRUCT(
        'pass',:v_cnt_pass,'pending',:v_cnt_pending,'rejected',:v_cnt_rejected,
        'skipped',:v_cnt_skipped,'duplicate',:v_cnt_dup,'pending_rechecked',:v_cnt_recheck);

    -- Complete run
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='COMPLETED',
        COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ, RESULT_SUMMARY=:v_summary
        WHERE RUN_ID=:v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG (RUN_ID,OPERATION,DETAIL,ACTOR)
        SELECT :v_run_id,'ONBOARD',:v_summary,:v_actor;
    DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;

    RETURN OBJECT_CONSTRUCT('STATUS','COMPLETED','RUN_ID',:v_run_id,
        'PASS',:v_cnt_pass,'PENDING',:v_cnt_pending,'REJECTED',:v_cnt_rejected,
        'SKIPPED',:v_cnt_skipped,'DUPLICATE',:v_cnt_dup,'PENDING_RECHECKED',:v_cnt_recheck);

EXCEPTION WHEN OTHER THEN
    BEGIN ROLLBACK; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ WHERE RUN_ID=:v_run_id; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG(RUN_ID,OPERATION,DETAIL,ACTOR) SELECT :v_run_id,'ONBOARD_ERROR',OBJECT_CONSTRUCT('error',SQLERRM),:v_actor; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token; EXCEPTION WHEN OTHER THEN NULL; END;
    RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON',SQLERRM,'ERROR_CODE',SQLCODE);
END;

-- E3. OFFBOARD ACCESS V2 ---------------------------------------------------
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_OFFBOARD_ACCESS_V2(P_KEY VARCHAR, P_DROP_ROLE BOOLEAN)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    v_ddl     VARCHAR;
    v_token    VARCHAR DEFAULT UUID_STRING();
    v_now      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_actor    VARCHAR DEFAULT CURRENT_USER();
    v_run_id   INTEGER;
    v_role     VARCHAR;
    v_map_cnt  INTEGER;
    v_prefix   VARCHAR;
    v_suffix   VARCHAR;
BEGIN
    IF (P_KEY IS NULL OR TRIM(P_KEY) = '') THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Empty key');
    END IF;
    IF (NOT REGEXP_LIKE(TRIM(P_KEY), '^[A-Za-z0-9_]+$')) THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Invalid key format');
    END IF;

    SELECT CONFIG_VALUE INTO :v_prefix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_PREFIX';
    SELECT CONFIG_VALUE INTO :v_suffix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_SUFFIX';
    v_role := :v_prefix || TRIM(P_KEY) || :v_suffix;

    -- Acquire mutex
    BEGIN
        INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX (LOCK_KEY,TOKEN,OWNER_SESSION,ACQUIRED_AT)
            VALUES ('X',:v_token,CURRENT_SESSION()::VARCHAR,:v_now);
    EXCEPTION WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Mutex held by another writer');
    END;

    -- Create run
    SELECT RAM_V2_EXAMPLE.GOVERNANCE.RUN_ID_SEQ.NEXTVAL INTO :v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS (RUN_ID, OPERATION,STARTED_AT,STATUS,ACTOR)
        VALUES (:v_run_id, 'OFFBOARD',:v_now,'RUNNING',:v_actor);

    -- Block key
    MERGE INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS k
    USING (SELECT TRIM(:P_KEY) AS mk) s ON k.MAPPING_KEY=s.mk
    WHEN MATCHED THEN UPDATE SET BLOCKED=TRUE, UPDATED_AT=:v_now
    WHEN NOT MATCHED THEN INSERT (MAPPING_KEY,BLOCKED,GENERATION,CREATED_AT,UPDATED_AT)
        VALUES (s.mk, TRUE, 1, :v_now, :v_now);

    -- Delete mapping
    DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY = TRIM(:P_KEY);

    -- Cancel pending and supersede pass requests for this key
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS
        SET STATUS='CANCELLED', REASON='Offboarded', RESOLVED_AT=:v_now, RESOLVED_BY_RUN_ID=:v_run_id
        WHERE MAPPING_KEY = TRIM(:P_KEY) AND STATUS IN ('PASS','PENDING');

    -- Clear MAPPING_KEY on governed rows for this key
    UPDATE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS
        SET MAPPING_KEY = NULL
        WHERE MAPPING_KEY = TRIM(:P_KEY);

    -- Revoke or drop role
    IF (P_DROP_ROLE) THEN
        BEGIN
            v_ddl := 'REVOKE SELECT ON TABLE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
        BEGIN
            v_ddl := 'REVOKE USAGE ON SCHEMA RAM_V2_EXAMPLE.SHARED FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
        BEGIN
            v_ddl := 'REVOKE USAGE ON DATABASE RAM_V2_EXAMPLE FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
        BEGIN
            v_ddl := 'DROP ROLE IF EXISTS "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
    ELSE
        -- Keep role, revoke SELECT only
        BEGIN
            v_ddl := 'REVOKE SELECT ON TABLE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
        BEGIN
            v_ddl := 'REVOKE USAGE ON SCHEMA RAM_V2_EXAMPLE.SHARED FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
        BEGIN
            v_ddl := 'REVOKE USAGE ON DATABASE RAM_V2_EXAMPLE FROM ROLE "' || :v_role || '"';
            EXECUTE IMMEDIATE :v_ddl;
        EXCEPTION WHEN OTHER THEN NULL; END;
    END IF;

    -- Audit and complete
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG (RUN_ID,OPERATION,DETAIL,ACTOR)
        SELECT :v_run_id,'OFFBOARD',OBJECT_CONSTRUCT('key',TRIM(:P_KEY),'role',:v_role,'drop_role',:P_DROP_ROLE),:v_actor;
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='COMPLETED',
        COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        RESULT_SUMMARY=OBJECT_CONSTRUCT('key',TRIM(:P_KEY),'role',:v_role,'dropped',:P_DROP_ROLE)
        WHERE RUN_ID=:v_run_id;
    DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;

    RETURN OBJECT_CONSTRUCT('STATUS','COMPLETED','RUN_ID',:v_run_id,'KEY',TRIM(P_KEY),'ROLE',:v_role);

EXCEPTION WHEN OTHER THEN
    BEGIN ROLLBACK; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ WHERE RUN_ID=:v_run_id; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token; EXCEPTION WHEN OTHER THEN NULL; END;
    RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON',SQLERRM);
END;

-- E4. REAUTHORIZE ACCESS V2 ------------------------------------------------
CREATE OR REPLACE PROCEDURE GOVERNANCE.SP_REAUTHORIZE_ACCESS_V2(P_KEY VARCHAR, P_REASON VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
    v_ddl     VARCHAR;
    v_token    VARCHAR DEFAULT UUID_STRING();
    v_now      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    v_actor    VARCHAR DEFAULT CURRENT_USER();
    v_run_id   INTEGER;
    v_role     VARCHAR;
    v_prefix   VARCHAR;
    v_suffix   VARCHAR;
    v_pair_cnt INTEGER;
BEGIN
    IF (P_KEY IS NULL OR TRIM(P_KEY) = '') THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Empty key');
    END IF;
    IF (P_REASON IS NULL OR LENGTH(TRIM(P_REASON)) < 10) THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Reason must be at least 10 characters');
    END IF;

    SELECT CONFIG_VALUE INTO :v_prefix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_PREFIX';
    SELECT CONFIG_VALUE INTO :v_suffix FROM RAM_V2_EXAMPLE.GOVERNANCE.CONFIG WHERE CONFIG_KEY='ROLE_SUFFIX';
    v_role := :v_prefix || TRIM(P_KEY) || :v_suffix;

    -- Acquire mutex
    BEGIN
        INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX (LOCK_KEY,TOKEN,OWNER_SESSION,ACQUIRED_AT)
            VALUES ('X',:v_token,CURRENT_SESSION()::VARCHAR,:v_now);
    EXCEPTION WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON','Mutex held by another writer');
    END;

    -- Create run
    SELECT RAM_V2_EXAMPLE.GOVERNANCE.RUN_ID_SEQ.NEXTVAL INTO :v_run_id;
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS (RUN_ID, OPERATION,STARTED_AT,STATUS,ACTOR)
        VALUES (:v_run_id, 'REAUTHORIZE',:v_now,'RUNNING',:v_actor);

    -- Unblock key, increment generation
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_KEYS
        SET BLOCKED=FALSE, GENERATION=GENERATION+1, UPDATED_AT=:v_now
        WHERE MAPPING_KEY=TRIM(:P_KEY);

    -- Ensure role exists with grants
    v_ddl := 'CREATE ROLE IF NOT EXISTS "' || :v_role || '"';
    EXECUTE IMMEDIATE :v_ddl;
    v_ddl := 'GRANT ROLE "' || :v_role || '" TO ROLE RAM_V2_ADMIN';
    EXECUTE IMMEDIATE :v_ddl;
    v_ddl := 'GRANT USAGE ON DATABASE RAM_V2_EXAMPLE TO ROLE "' || :v_role || '"';
    EXECUTE IMMEDIATE :v_ddl;
    v_ddl := 'GRANT USAGE ON SCHEMA RAM_V2_EXAMPLE.SHARED TO ROLE "' || :v_role || '"';
    EXECUTE IMMEDIATE :v_ddl;
    v_ddl := 'GRANT SELECT ON TABLE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS TO ROLE "' || :v_role || '"';
    EXECUTE IMMEDIATE :v_ddl;

    -- Restore mapping from existing pair assignments
    MERGE INTO RAM_V2_EXAMPLE.GOVERNANCE.ACCESS_MAPPING m
    USING (SELECT TRIM(:P_KEY) AS mk, :v_role AS rn) s
        ON m.MAPPING_KEY = s.mk AND m.ROLE_NAME = s.rn
    WHEN NOT MATCHED THEN INSERT (MAPPING_KEY, ROLE_NAME, CREATED_AT) VALUES (s.mk, s.rn, :v_now);

    -- Restore MAPPING_KEY on governed rows from pair assignments
    UPDATE RAM_V2_EXAMPLE.SHARED.GOVERNED_STOCK_MOVEMENTS g
        SET MAPPING_KEY = a.MAPPING_KEY
    FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
    WHERE g.PRODUCT_ID = a.PRODUCT_ID AND g.SUPPLIER_ID = a.SUPPLIER_ID
      AND a.MAPPING_KEY = TRIM(:P_KEY)
      AND (g.MAPPING_KEY IS NULL OR g.MAPPING_KEY != a.MAPPING_KEY);

    -- Create new PASS request
    SELECT COUNT(*) INTO :v_pair_cnt FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS
        WHERE MAPPING_KEY=TRIM(:P_KEY);
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.V2_REQUESTS
        (RUN_ID, PRODUCT_ID, SUPPLIER_ID, MAPPING_KEY, ROLE_NAME, STATUS, REASON, CREATED_AT, RESOLVED_AT, RESOLVED_BY_RUN_ID)
    SELECT :v_run_id, a.PRODUCT_ID, a.SUPPLIER_ID, a.MAPPING_KEY, :v_role,
        'PASS', 'Reauthorized: ' || TRIM(:P_REASON), :v_now, :v_now, :v_run_id
    FROM RAM_V2_EXAMPLE.GOVERNANCE.PAIR_ASSIGNMENTS a
    WHERE a.MAPPING_KEY = TRIM(:P_KEY);

    -- Audit and complete
    INSERT INTO RAM_V2_EXAMPLE.GOVERNANCE.AUDIT_LOG (RUN_ID,OPERATION,DETAIL,ACTOR)
        SELECT :v_run_id,'REAUTHORIZE',OBJECT_CONSTRUCT('key',TRIM(:P_KEY),'role',:v_role,
            'reason',TRIM(:P_REASON),'pair_count',:v_pair_cnt),:v_actor;
    UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='COMPLETED',
        COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        RESULT_SUMMARY=OBJECT_CONSTRUCT('key',TRIM(:P_KEY),'role',:v_role,'pairs_restored',:v_pair_cnt)
        WHERE RUN_ID=:v_run_id;
    DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token;

    RETURN OBJECT_CONSTRUCT('STATUS','COMPLETED','RUN_ID',:v_run_id,'KEY',TRIM(P_KEY),'PAIRS_RESTORED',:v_pair_cnt);

EXCEPTION WHEN OTHER THEN
    BEGIN ROLLBACK; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN UPDATE RAM_V2_EXAMPLE.GOVERNANCE.V2_RUNS SET STATUS='FAILED',COMPLETED_AT=CURRENT_TIMESTAMP()::TIMESTAMP_NTZ WHERE RUN_ID=:v_run_id; EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN DELETE FROM RAM_V2_EXAMPLE.GOVERNANCE.V2_MUTEX WHERE TOKEN=:v_token; EXCEPTION WHEN OTHER THEN NULL; END;
    RETURN OBJECT_CONSTRUCT('STATUS','FAILED','REASON',SQLERRM);
END;

-- ============================================================
-- F. REFRESH TASK (created SUSPENDED)
-- ============================================================
CREATE OR REPLACE TASK RAM_V2_EXAMPLE.GOVERNANCE.REFRESH_GOVERNED_COPY_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = 'USING CRON 0 */6 * * * Australia/Sydney'
AS
    CALL RAM_V2_EXAMPLE.GOVERNANCE.SP_REFRESH_GOVERNED_COPY();

-- Task is SUSPENDED by design; do not resume until acceptance
SELECT 'Objects created successfully' AS STATUS;
