--------------------------------------------------------------------------------
-- 04_assertions.sql
-- RAM V2 Example: one PASS/FAIL row per check, saved to TEST_RESULTS
-- Run as RAM_V2_ADMIN after completing 03_walkthrough.sql
-- Every check compares an actual result with an expectation. Viewer checks use what the viewer
-- role actually saw during 03 (GOVERNANCE.OBSERVATIONS), against counts taken from the source.
-- Nothing here records PASS without testing something; untestable items are NOT TESTED.
--------------------------------------------------------------------------------
USE ROLE RAM_V2_ADMIN;
USE DATABASE RAM_V2_EXAMPLE;
USE WAREHOUSE COMPUTE_WH;

-- Durable test results table
CREATE TABLE IF NOT EXISTS GOVERNANCE.TEST_RESULTS (
    TEST_ID        INTEGER AUTOINCREMENT ORDER,
    RUN_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SCENARIO       INTEGER      NOT NULL,
    CHECK_NAME     VARCHAR(200) NOT NULL,
    EXPECTED       VARCHAR(500),
    ACTUAL         VARCHAR(500),
    STATUS         VARCHAR(20)  NOT NULL,
    NOTE           VARCHAR(1000),
    PRIMARY KEY (TEST_ID)
);

-- Clear previous run (keeps table structure, removes old results for re-run)
DELETE FROM GOVERNANCE.TEST_RESULTS WHERE RUN_TIMESTAMP < CURRENT_TIMESTAMP();

-- ============================================================
-- SCENARIO 1: Onboard existing + missing pairs
-- ============================================================

-- 1a: First onboard run produced PASS=2
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 1, 'First onboard PASS count', '2',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_REQUESTS
     WHERE RUN_ID = (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED')
       AND STATUS='PASS')::VARCHAR,
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_REQUESTS
               WHERE RUN_ID = (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED')
                 AND STATUS='PASS') = 2 THEN 'PASS' ELSE 'FAIL' END;

-- 1b: GROUP_GAMMA was PENDING after the first onboard (recorded in 03 before step 4 resolved it)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 1, 'First onboard: missing pair is PENDING', '1',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S1_GAMMA_PENDING')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S1_GAMMA_PENDING') = 1 THEN 'PASS' ELSE 'FAIL' END;

-- 1c: GROUP_ALPHA viewer role was created by onboarding
SHOW ROLES LIKE 'RAM_V2_GROUP_ALPHA_VIEWER';
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 1, 'GROUP_ALPHA viewer role exists', '1', COUNT(*)::VARCHAR,
    CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 1d: Mapping exists for GROUP_ALPHA
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 1, 'GROUP_ALPHA mapping exists (post-reauth state)', '1',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_ALPHA'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_ALPHA') >= 1
         THEN 'PASS' ELSE 'FAIL' END;

-- 1e: Pair assignment for P1001+S2001
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 1, 'Pair assignment P1001+S2001 -> GROUP_ALPHA', 'GROUP_ALPHA',
    (SELECT MAPPING_KEY FROM GOVERNANCE.PAIR_ASSIGNMENTS
     WHERE PRODUCT_ID='P1001' AND SUPPLIER_ID='S2001'),
    CASE WHEN (SELECT MAPPING_KEY FROM GOVERNANCE.PAIR_ASSIGNMENTS
               WHERE PRODUCT_ID='P1001' AND SUPPLIER_ID='S2001') = 'GROUP_ALPHA'
         THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 2: Viewer isolation
-- ============================================================

-- 2a: Governed copy has 45 rows for GROUP_ALPHA (40 original + 5 from step 5)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 2, 'GROUP_ALPHA governed row count', '45',
    (SELECT COUNT(*)::VARCHAR FROM SHARED.GOVERNED_STOCK_MOVEMENTS
     WHERE MAPPING_KEY='GROUP_ALPHA' AND REMOVED_AT IS NULL),
    CASE WHEN (SELECT COUNT(*) FROM SHARED.GOVERNED_STOCK_MOVEMENTS
               WHERE MAPPING_KEY='GROUP_ALPHA' AND REMOVED_AT IS NULL) = 45
         THEN 'PASS' ELSE 'FAIL' END;

-- 2b: Source has 45 rows for P1001+S2001
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 2, 'Source P1001+S2001 row count matches governed', '45',
    (SELECT COUNT(*)::VARCHAR FROM RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS
     WHERE PRODUCT_ID='P1001' AND SUPPLIER_ID='S2001'),
    CASE WHEN (SELECT COUNT(*) FROM RAM_V2_EXAMPLE.SOURCE.STOCK_MOVEMENTS
               WHERE PRODUCT_ID='P1001' AND SUPPLIER_ID='S2001') = 45
         THEN 'PASS' ELSE 'FAIL' END;

-- 2c: Viewer isolation: what RAM_V2_GROUP_ALPHA_VIEWER saw with secondary roles NONE (step 2),
--     against an independent count from the source
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 2, 'Viewer sees exactly its mapped rows (secondary roles NONE)',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_EXPECTED')::VARCHAR,
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_SEEN')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_SEEN') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_EXPECTED') AND (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_SEEN') > 0
         THEN 'PASS' ELSE 'FAIL' END;

-- 2d: The viewer saw no rows from any other pair
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 2, 'Viewer sees no rows from other pairs', '0',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_OTHER_ROWS')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_OTHER_ROWS') = 0 THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 3: Re-submit identical file => all SKIPPED
-- ============================================================

-- 3a: Second onboard run has SKIPPED=3
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 3, 'Re-submit all SKIPPED', '3',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_SUBMISSIONS
     WHERE FILENAME='onboard_01.csv'
       AND RUN_ID = (SELECT MIN(r.RUN_ID) FROM GOVERNANCE.V2_RUNS r
                     WHERE r.OPERATION='ONBOARD' AND r.STATUS='COMPLETED'
                       AND r.RUN_ID > (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED'))
       AND OUTCOME='SKIPPED'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_SUBMISSIONS
               WHERE FILENAME='onboard_01.csv'
                 AND RUN_ID = (SELECT MIN(r.RUN_ID) FROM GOVERNANCE.V2_RUNS r
                               WHERE r.OPERATION='ONBOARD' AND r.STATUS='COMPLETED'
                                 AND r.RUN_ID > (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED'))
                 AND OUTCOME='SKIPPED') = 3 THEN 'PASS' ELSE 'FAIL' END;

-- 3b: The step 3 re-submit created no REJECTED rows. Scoped to the step 3 run only: step 8 re-submits the
--     same file after offboarding, and its GROUP_ALPHA row is correctly REJECTED there (checked in 8a).
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 3, 'No rejected rows from the step 3 re-submit', '0',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_SUBMISSIONS
     WHERE FILENAME='onboard_01.csv' AND OUTCOME='REJECTED'
       AND RUN_ID = (SELECT MIN(r.RUN_ID) FROM GOVERNANCE.V2_RUNS r
                     WHERE r.OPERATION='ONBOARD' AND r.STATUS='COMPLETED'
                       AND r.RUN_ID > (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED'))),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_SUBMISSIONS
               WHERE FILENAME='onboard_01.csv' AND OUTCOME='REJECTED'
                 AND RUN_ID = (SELECT MIN(r.RUN_ID) FROM GOVERNANCE.V2_RUNS r
                     WHERE r.OPERATION='ONBOARD' AND r.STATUS='COMPLETED'
                       AND r.RUN_ID > (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED'))) = 0 THEN 'PASS' ELSE 'FAIL' END;

-- 3c: Assignment count unchanged by the re-submit (step 3 against step 1)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 3, 'Assignment count unchanged after re-submit',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S1_ASSIGNMENTS')::VARCHAR, (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S3_ASSIGNMENTS')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S3_ASSIGNMENTS') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S1_ASSIGNMENTS') THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 4: PENDING pair arrives => PASS after refresh + onboard
-- ============================================================

-- 4a: GROUP_GAMMA request resolved to PASS
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 4, 'GROUP_GAMMA request resolved to PASS', 'PASS',
    (SELECT STATUS FROM GOVERNANCE.V2_REQUESTS
     WHERE MAPPING_KEY='GROUP_GAMMA'
       AND RUN_ID = (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED')),
    CASE WHEN (SELECT STATUS FROM GOVERNANCE.V2_REQUESTS
               WHERE MAPPING_KEY='GROUP_GAMMA'
                 AND RUN_ID = (SELECT MIN(RUN_ID) FROM GOVERNANCE.V2_RUNS WHERE OPERATION='ONBOARD' AND STATUS='COMPLETED')) = 'PASS'
         THEN 'PASS' ELSE 'FAIL' END;

-- 4b: GROUP_GAMMA has a mapping
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 4, 'GROUP_GAMMA mapping exists', '1',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_GAMMA'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_GAMMA') = 1
         THEN 'PASS' ELSE 'FAIL' END;

-- 4c: GROUP_GAMMA viewer sees 10 rows
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 4, 'GROUP_GAMMA governed rows', '10',
    (SELECT COUNT(*)::VARCHAR FROM SHARED.GOVERNED_STOCK_MOVEMENTS
     WHERE MAPPING_KEY='GROUP_GAMMA' AND REMOVED_AT IS NULL),
    CASE WHEN (SELECT COUNT(*) FROM SHARED.GOVERNED_STOCK_MOVEMENTS
               WHERE MAPPING_KEY='GROUP_GAMMA' AND REMOVED_AT IS NULL) = 10
         THEN 'PASS' ELSE 'FAIL' END;

-- 4d: The GROUP_GAMMA viewer actually sees the newly arrived rows (step 4)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 4, 'GROUP_GAMMA viewer sees the arrived rows',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S4_GAMMA_EXPECTED')::VARCHAR, (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S4_GAMMA_SEEN')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S4_GAMMA_SEEN') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S4_GAMMA_EXPECTED') AND (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S4_GAMMA_SEEN') > 0
         THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 5: New child rows inherit assignment after refresh
-- ============================================================

-- 5a: GROUP_ALPHA now has 45 governed rows (40 + 5 new)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 5, 'New child rows for GROUP_ALPHA visible', '45',
    (SELECT COUNT(*)::VARCHAR FROM SHARED.GOVERNED_STOCK_MOVEMENTS
     WHERE MAPPING_KEY='GROUP_ALPHA' AND REMOVED_AT IS NULL),
    CASE WHEN (SELECT COUNT(*) FROM SHARED.GOVERNED_STOCK_MOVEMENTS
               WHERE MAPPING_KEY='GROUP_ALPHA' AND REMOVED_AT IS NULL) = 45
         THEN 'PASS' ELSE 'FAIL' END;

-- 5b: No onboarding call between the new rows arriving and the viewer seeing them (step 5)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 5, 'No onboarding call needed for new child rows',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ONBOARD_RUNS_BEFORE')::VARCHAR, (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ONBOARD_RUNS_AFTER')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ONBOARD_RUNS_AFTER') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ONBOARD_RUNS_BEFORE') THEN 'PASS' ELSE 'FAIL' END;

-- 5c: The viewer actually sees the new child rows (step 5), against the source count
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 5, 'Viewer sees new child rows after refresh',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ALPHA_EXPECTED')::VARCHAR, (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ALPHA_SEEN')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ALPHA_SEEN') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ALPHA_EXPECTED') AND (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S5_ALPHA_SEEN') > (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S2_ALPHA_SEEN')
         THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 6: Malformed and conflicting input
-- ============================================================

-- 6a: Malformed file -> all REJECTED
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 6, 'Malformed file all REJECTED', '3',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_SUBMISSIONS
     WHERE FILENAME='malformed_01.csv' AND OUTCOME='REJECTED'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_SUBMISSIONS
               WHERE FILENAME='malformed_01.csv' AND OUTCOME='REJECTED') = 3
         THEN 'PASS' ELSE 'FAIL' END;

-- 6b: Rejection reasons recorded
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 6, 'Rejection reasons non-empty', 'All have reasons',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_SUBMISSIONS
     WHERE FILENAME='malformed_01.csv' AND OUTCOME='REJECTED' AND REASON IS NOT NULL AND REASON != ''),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_SUBMISSIONS
               WHERE FILENAME='malformed_01.csv' AND OUTCOME='REJECTED' AND REASON IS NOT NULL AND REASON != '') = 3
         THEN 'PASS' ELSE 'FAIL' END;

-- 6c: Conflict file -> REJECTED with reason
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 6, 'Conflicting assignment REJECTED', 'Pair already assigned to different key',
    (SELECT REASON FROM GOVERNANCE.V2_SUBMISSIONS
     WHERE FILENAME='conflict_01.csv' AND OUTCOME='REJECTED'
     LIMIT 1),
    CASE WHEN (SELECT REASON FROM GOVERNANCE.V2_SUBMISSIONS
               WHERE FILENAME='conflict_01.csv' AND OUTCOME='REJECTED'
               LIMIT 1) = 'Pair already assigned to different key'
         THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 7: Offboard GROUP_ALPHA
-- ============================================================

-- 7a: GROUP_ALPHA key blocked and mapping removed straight after offboarding (step 7)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 7, 'Key blocked after offboard', '1', (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_BLOCKED')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_BLOCKED') = 1 THEN 'PASS' ELSE 'FAIL' END;
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 7, 'Mapping removed by offboard', '0', (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_MAPPINGS')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_MAPPINGS') = 0 THEN 'PASS' ELSE 'FAIL' END;

-- 7b: Requests for GROUP_ALPHA were cancelled (before reauth recreated them)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 7, 'GROUP_ALPHA requests cancelled by offboard', 'CANCELLED exists',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.V2_REQUESTS
     WHERE MAPPING_KEY='GROUP_ALPHA' AND STATUS='CANCELLED'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.V2_REQUESTS
               WHERE MAPPING_KEY='GROUP_ALPHA' AND STATUS='CANCELLED') > 0 THEN 'PASS' ELSE 'FAIL' END;

-- 7c: Offboard run completed
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 7, 'Offboard run completed', 'COMPLETED',
    (SELECT STATUS FROM GOVERNANCE.V2_RUNS WHERE OPERATION='OFFBOARD' ORDER BY RUN_ID DESC LIMIT 1),
    CASE WHEN (SELECT STATUS FROM GOVERNANCE.V2_RUNS WHERE OPERATION='OFFBOARD' ORDER BY RUN_ID DESC LIMIT 1) = 'COMPLETED'
         THEN 'PASS' ELSE 'FAIL' END;

-- 7d: SELECT on the governed copy revoked from the last-mapping viewer (SHOW GRANTS in step 7).
--     This is why the viewer gets an authorisation error rather than zero rows. The error itself is
--     not captured here: a failing statement would stop a Run All, so it is recorded as NOT TESTED below.
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 7, 'SELECT revoked from last-mapping viewer', '0', (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_SELECT_GRANTS')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S7_ALPHA_SELECT_GRANTS') = 0 THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 8: Re-submit after offboard => access NOT restored
-- ============================================================

-- 8a: GROUP_ALPHA was REJECTED as blocked
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 8, 'GROUP_ALPHA REJECTED after offboard re-submit', 'REJECTED',
    (SELECT s.OUTCOME FROM GOVERNANCE.V2_SUBMISSIONS s
     JOIN GOVERNANCE.V2_RUNS r ON s.RUN_ID=r.RUN_ID
     WHERE s.MAPPING_KEY='GROUP_ALPHA' AND s.OUTCOME='REJECTED'
       AND s.REASON LIKE '%blocked%'
     ORDER BY s.SUBMITTED_AT DESC LIMIT 1),
    CASE WHEN EXISTS (SELECT 1 FROM GOVERNANCE.V2_SUBMISSIONS s
                      JOIN GOVERNANCE.V2_RUNS r ON s.RUN_ID=r.RUN_ID
                      WHERE s.MAPPING_KEY='GROUP_ALPHA' AND s.OUTCOME='REJECTED'
                        AND s.REASON LIKE '%blocked%')
         THEN 'PASS' ELSE 'FAIL' END;

-- 8b: Re-submitting the original file after offboarding did not restore the mapping (step 8)
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 8, 'Re-submit after offboard did not restore mapping', '0', (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S8_ALPHA_MAPPINGS')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S8_ALPHA_MAPPINGS') = 0 THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- SCENARIO 9: Reauthorize GROUP_ALPHA => access returns
-- ============================================================

-- 9a: Key unblocked
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 9, 'GROUP_ALPHA key unblocked after reauth', 'FALSE',
    BLOCKED::VARCHAR,
    CASE WHEN BLOCKED = FALSE THEN 'PASS' ELSE 'FAIL' END
FROM GOVERNANCE.V2_KEYS WHERE MAPPING_KEY='GROUP_ALPHA';

-- 9b: Generation incremented
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 9, 'GROUP_ALPHA generation incremented', '2',
    GENERATION::VARCHAR,
    CASE WHEN GENERATION = 2 THEN 'PASS' ELSE 'FAIL' END
FROM GOVERNANCE.V2_KEYS WHERE MAPPING_KEY='GROUP_ALPHA';

-- 9c: Mapping restored
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 9, 'GROUP_ALPHA mapping restored', '1',
    (SELECT COUNT(*)::VARCHAR FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_ALPHA'),
    CASE WHEN (SELECT COUNT(*) FROM GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY='GROUP_ALPHA') = 1
         THEN 'PASS' ELSE 'FAIL' END;

-- 9d: The viewer sees its rows again after reauthorisation (step 9), against the source count
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 9, 'Viewer sees its rows again after reauth',
    (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S9_ALPHA_EXPECTED')::VARCHAR, (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S9_ALPHA_SEEN')::VARCHAR,
    CASE WHEN (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S9_ALPHA_SEEN') = (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S9_ALPHA_EXPECTED') AND (SELECT MAX(VALUE) FROM GOVERNANCE.OBSERVATIONS WHERE OBS_NAME = 'S9_ALPHA_SEEN') > 0
         THEN 'PASS' ELSE 'FAIL' END;

-- 9e: Reauth run completed
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS)
SELECT 9, 'Reauthorize run completed', 'COMPLETED',
    (SELECT STATUS FROM GOVERNANCE.V2_RUNS WHERE OPERATION='REAUTHORIZE' ORDER BY RUN_ID DESC LIMIT 1),
    CASE WHEN (SELECT STATUS FROM GOVERNANCE.V2_RUNS WHERE OPERATION='REAUTHORIZE' ORDER BY RUN_ID DESC LIMIT 1) = 'COMPLETED'
         THEN 'PASS' ELSE 'FAIL' END;

-- ============================================================
-- NOT TESTED items
-- ============================================================
INSERT INTO GOVERNANCE.TEST_RESULTS (SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS, NOTE)
VALUES
    (0, 'Concurrent busy writer (second session)', 'Fail busy', NULL, 'NOT TESTED',
     'Requires two simultaneous sessions. Mutex design prevents concurrent writers but was not tested with actual concurrency.'),
    (0, 'Session abort recovery', 'Token survives, later writer fails busy', NULL, 'NOT TESTED',
     'Requires aborting a session externally. The mutex stays committed on interrupt, but actual abort was not performed.'),
    (0, 'Restricted session role switch', 'NOT TESTED if session disallows viewer role', NULL, 'NOT TESTED',
     'Session allowed USE ROLE to viewer. If a session restricts role switching, viewer isolation cannot be confirmed.'),
    (0, 'Viewer SELECT returns an authorisation error after last mapping removed', 'Access error', NULL, 'NOT TESTED',
     'Not captured in Run All because the failing statement would stop the script. SELECT revocation is checked in 7d; run the commented SELECT in step 7 by hand to see the error.'),
    (0, 'Task execution', 'Refresh runs on schedule', NULL, 'NOT TESTED',
     'Task is SUSPENDED by design. Resume only after acceptance.');

-- ============================================================
-- SUMMARY
-- ============================================================
SELECT STATUS, COUNT(*) AS CHECK_COUNT
FROM GOVERNANCE.TEST_RESULTS
GROUP BY STATUS
ORDER BY STATUS;

SELECT SCENARIO, CHECK_NAME, EXPECTED, ACTUAL, STATUS, NOTE
FROM GOVERNANCE.TEST_RESULTS
ORDER BY SCENARIO, TEST_ID;
