-- Worked example B, step 3 of 4: the key is already on every row, so the CSV only maps keys to roles.
-- Onboard, look through each role's eyes, survive the pipeline team rebuilding their table (changed
-- keys follow the source, new rows are visible immediately), offboard. Every role's view is captured
-- into a session variable with secondary roles OFF.

USE ROLE RAP_KEYED_ADMIN;
USE SECONDARY ROLES NONE;
USE WAREHOUSE RAP_KEYED_WH;
SET ME = CURRENT_USER();

---------------------------------------------------------------------------------------------------
-- 1. Onboard from CSV. Two columns: MAPPING_KEY, ROLE_NAME. No record IDs: the rows already carry the key.
---------------------------------------------------------------------------------------------------
COPY INTO @RAP_KEYED.GOVERNANCE.ACCESS_REQUESTS/request_01.csv FROM (
  SELECT * FROM VALUES
    ('NORTH', 'RAP_KEYED_NORTH_TEAM'),
    ('SOUTH', 'RAP_KEYED_SOUTH_TEAM'),
    ('EAST',  'RAP_KEYED_SOUTH_TEAM'),
    ('EAST',  'RAP_KEYED_EAST_TEAM')
  AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- request_02 breaks every rule once, plus one valid row (WEST) that must NOT be applied, because a
-- file with any failure is rejected whole.
COPY INTO @RAP_KEYED.GOVERNANCE.ACCESS_REQUESTS/request_02.csv FROM (
  SELECT * FROM VALUES
    ('WEST',        'RAP_KEYED_WEST_TEAM'),
    ('NROTH',       'RAP_KEYED_NORTH_TEAM'),
    ('west region', 'RAP_KEYED_WEST_TEAM'),
    ('WEST',        'rap_keyed_west_team'),
    ('WEST',        'X; DROP TABLE RAP_KEYED.SHARED.SERVICE_TICKETS')
  AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- Expect: 4 mappings, 3 roles. WEST is mapped to nobody.
CALL RAP_KEYED.GOVERNANCE.SP_ONBOARD_ACCESS('request_01.csv');
SET ONBOARD_1 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

-- Re-running the same file changes nothing.
CALL RAP_KEYED.GOVERNANCE.SP_ONBOARD_ACCESS('request_01.csv');
SET ONBOARD_RERUN = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

-- Expect: whole file rejected, 4 of 5 rows logged, nothing applied.
CALL RAP_KEYED.GOVERNANCE.SP_ONBOARD_ACCESS('request_02.csv');
SET ONBOARD_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SHOW ROLES LIKE 'RAP_KEYED_WEST_TEAM';
SET WEST_ROLE_CREATED = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SET WEST_MAPPINGS = (SELECT COUNT(*) FROM RAP_KEYED.GOVERNANCE.ACCESS_MAPPING WHERE MAPPING_KEY = 'WEST');

---------------------------------------------------------------------------------------------------
-- 2. Test roles, set up the way a consumer's own onboarding would: assign to a user, give compute.
--    A control role has SELECT directly but no mapping; an auditor role is exempt from the policy.
---------------------------------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS RAP_KEYED_NO_MAPPING;
CREATE ROLE IF NOT EXISTS RAP_KEYED_AUDITOR;
GRANT USAGE ON DATABASE RAP_KEYED TO ROLE RAP_KEYED_NO_MAPPING;
GRANT USAGE ON SCHEMA RAP_KEYED.SHARED TO ROLE RAP_KEYED_NO_MAPPING;
GRANT SELECT ON TABLE RAP_KEYED.SHARED.SERVICE_TICKETS TO ROLE RAP_KEYED_NO_MAPPING;
GRANT USAGE ON DATABASE RAP_KEYED TO ROLE RAP_KEYED_AUDITOR;
GRANT USAGE ON SCHEMA RAP_KEYED.SHARED TO ROLE RAP_KEYED_AUDITOR;
GRANT SELECT ON TABLE RAP_KEYED.SHARED.SERVICE_TICKETS TO ROLE RAP_KEYED_AUDITOR;
GRANT ROLE RAP_KEYED_NORTH_TEAM TO USER IDENTIFIER($ME);
GRANT ROLE RAP_KEYED_SOUTH_TEAM TO USER IDENTIFIER($ME);
GRANT ROLE RAP_KEYED_EAST_TEAM  TO USER IDENTIFIER($ME);
GRANT ROLE RAP_KEYED_NO_MAPPING TO USER IDENTIFIER($ME);
GRANT ROLE RAP_KEYED_AUDITOR    TO USER IDENTIFIER($ME);
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE RAP_KEYED_NORTH_TEAM;
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE RAP_KEYED_SOUTH_TEAM;
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE RAP_KEYED_EAST_TEAM;
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE RAP_KEYED_NO_MAPPING;
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE RAP_KEYED_AUDITOR;
GRANT USAGE ON WAREHOUSE RAP_KEYED_WH TO ROLE SYSADMIN;

---------------------------------------------------------------------------------------------------
-- 3. Look through each role's eyes.
---------------------------------------------------------------------------------------------------
SET ADMIN_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);   -- admin is exempt

USE ROLE RAP_KEYED_NORTH_TEAM;  USE SECONDARY ROLES NONE;
SET NORTH_KEYS = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
SET NORTH_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
-- A viewer cannot see, let alone change, the mapping.
EXECUTE IMMEDIATE $$
BEGIN
  INSERT INTO RAP_KEYED.GOVERNANCE.ACCESS_MAPPING (MAPPING_KEY, ROLE_NAME) VALUES ('WEST', 'RAP_KEYED_NORTH_TEAM');
  RETURN 'WROTE';
EXCEPTION
  WHEN OTHER THEN RETURN 'DENIED';
END;
$$;
SET VIEWER_WRITE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_KEYED_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_KEYS = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
SET SOUTH_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

USE ROLE RAP_KEYED_EAST_TEAM;   USE SECONDARY ROLES NONE;
SET EAST_KEYS = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
SET EAST_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

USE ROLE RAP_KEYED_NO_MAPPING;  USE SECONDARY ROLES NONE;
SET NOMAP_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
-- Consumers are never given the pipeline team's table.
EXECUTE IMMEDIATE $$
BEGIN
  LET n INTEGER := (SELECT COUNT(*) FROM RAP_KEYED.SOURCE.SERVICE_TICKETS);
  RETURN 'READ';
EXCEPTION
  WHEN OTHER THEN RETURN 'DENIED';
END;
$$;
SET NOMAP_SOURCE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_KEYED_AUDITOR;     USE SECONDARY ROLES NONE;
SET AUDITOR_ROWS = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

-- SYSADMIN inherits every viewer role (they were granted to it), so it sees all MAPPED rows.
USE ROLE SYSADMIN;             USE SECONDARY ROLES NONE;
SET SYSADMIN_KEYS = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;

---------------------------------------------------------------------------------------------------
-- 4. The pipeline team rebuilds their table. First a half-built rebuild (empty table), which the
--    refresh must refuse; then a real rebuild that adds T-1005 (already keyed NORTH), drops T-2003,
--    changes T-1001's status and moves T-4001 from WEST to NORTH.
---------------------------------------------------------------------------------------------------
USE ROLE RAP_KEYED_PIPELINE;    USE SECONDARY ROLES NONE;
CREATE OR REPLACE TABLE RAP_KEYED.SOURCE.SERVICE_TICKETS (
  TICKET_ID VARCHAR, OPENED_ON DATE, CATEGORY VARCHAR, STATUS VARCHAR, REGION_CODE VARCHAR);
GRANT SELECT ON TABLE RAP_KEYED.SOURCE.SERVICE_TICKETS TO ROLE RAP_KEYED_ADMIN;

USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_KEYED.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFUSED = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SET COPY_AFTER_REFUSE = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

USE ROLE RAP_KEYED_PIPELINE;    USE SECONDARY ROLES NONE;
CREATE OR REPLACE TABLE RAP_KEYED.SOURCE.SERVICE_TICKETS (
  TICKET_ID VARCHAR, OPENED_ON DATE, CATEGORY VARCHAR, STATUS VARCHAR, REGION_CODE VARCHAR);
INSERT INTO RAP_KEYED.SOURCE.SERVICE_TICKETS VALUES
  ('T-1001', '2026-01-05', 'Repair',       'Reopened', 'NORTH'),
  ('T-1002', '2026-01-08', 'Installation', 'Open',     'NORTH'),
  ('T-1003', '2026-01-12', 'Inspection',   'Open',     'NORTH'),
  ('T-1004', '2026-01-19', 'Repair',       'Closed',   'NORTH'),
  ('T-1005', '2026-02-02', 'Repair',       'Open',     'NORTH'),
  ('T-2001', '2026-01-06', 'Repair',       'Open',     'SOUTH'),
  ('T-2002', '2026-01-14', 'Inspection',   'Closed',   'SOUTH'),
  ('T-3001', '2026-01-07', 'Repair',       'Open',     'EAST'),
  ('T-3002', '2026-01-15', 'Repair',       'Closed',   'EAST'),
  ('T-3003', '2026-01-22', 'Inspection',   'Open',     'EAST'),
  ('T-4001', '2026-01-09', 'Installation', 'Open',     'NORTH'),
  ('T-4002', '2026-01-16', 'Repair',       'Closed',   'WEST');
GRANT SELECT ON TABLE RAP_KEYED.SOURCE.SERVICE_TICKETS TO ROLE RAP_KEYED_ADMIN;

-- The rebuild touched only their table: the governed copy and its assignments are untouched.
USE ROLE RAP_KEYED_NORTH_TEAM;  USE SECONDARY ROLES NONE;
SET NORTH_ROWS_BEFORE_REFRESH = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

-- Refresh (the scheduled task runs this same call; on demand: EXECUTE TASK ...TSK_REFRESH_SERVICE_TICKETS).
USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_KEYED.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFRESH_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_KEYED_NORTH_TEAM;  USE SECONDARY ROLES NONE;
-- The key comes from the data: the new row (T-1005) and the moved row (T-4001) are visible at once,
-- with no CSV, and the changed row carries its new status.
SET NORTH_ROWS_REFRESHED = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
SET NORTH_T1001 = (SELECT STATUS FROM RAP_KEYED.SHARED.SERVICE_TICKETS WHERE TICKET_ID = 'T-1001');
USE ROLE RAP_KEYED_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_ROWS_REFRESHED = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);   -- T-2003 gone

-- Soft delete: T-2003 left the source, so viewers no longer see it, but the row is still in the
-- governed copy (admin view).
USE ROLE RAP_KEYED_ADMIN;      USE SECONDARY ROLES NONE;
SET REMOVED_STATE = (SELECT REGION_CODE || '|' || IFF(REMOVED_AT IS NOT NULL, 'removed', 'live')
                     FROM RAP_KEYED.SHARED.SERVICE_TICKETS WHERE TICKET_ID = 'T-2003');

---------------------------------------------------------------------------------------------------
-- 4b. The record comes back (a partial rebuild, say). It is restored with its key: no CSV needed.
---------------------------------------------------------------------------------------------------
USE ROLE RAP_KEYED_PIPELINE;    USE SECONDARY ROLES NONE;
INSERT INTO RAP_KEYED.SOURCE.SERVICE_TICKETS VALUES ('T-2003', '2026-01-21', 'Installation', 'Open', 'SOUTH');

USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_KEYED.GOVERNANCE.SP_REFRESH_FROM_SOURCE();
SET REFRESH_3 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_KEYED_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_ROWS_RESTORED = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;

---------------------------------------------------------------------------------------------------
-- 5. Offboarding. Access ends on the next query; data is never deleted.
---------------------------------------------------------------------------------------------------
COPY INTO @RAP_KEYED.GOVERNANCE.ACCESS_REQUESTS/offboard_01.csv FROM (
  SELECT * FROM VALUES ('EAST', 'RAP_KEYED_SOUTH_TEAM') AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

-- offboard_02: one real mapping, one that never existed. Rejected whole.
COPY INTO @RAP_KEYED.GOVERNANCE.ACCESS_REQUESTS/offboard_02.csv FROM (
  SELECT * FROM VALUES
    ('EAST', 'RAP_KEYED_EAST_TEAM'),
    ('WEST', 'RAP_KEYED_WEST_TEAM')
  AS t(MAPPING_KEY, ROLE_NAME)
)
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = NONE)
HEADER = TRUE SINGLE = TRUE OVERWRITE = TRUE;

CALL RAP_KEYED.GOVERNANCE.SP_OFFBOARD_ACCESS_FILE('offboard_01.csv', FALSE);
SET OFFBOARD_1 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
CALL RAP_KEYED.GOVERNANCE.SP_OFFBOARD_ACCESS_FILE('offboard_02.csv', FALSE);
SET OFFBOARD_2 = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

USE ROLE RAP_KEYED_SOUTH_TEAM;  USE SECONDARY ROLES NONE;
SET SOUTH_KEYS_AFTER = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);
USE ROLE RAP_KEYED_EAST_TEAM;   USE SECONDARY ROLES NONE;
SET EAST_KEYS_AFTER = (SELECT LISTAGG(DISTINCT REGION_CODE, ',') WITHIN GROUP (ORDER BY REGION_CODE) FROM RAP_KEYED.SHARED.SERVICE_TICKETS);

-- Single-mapping call, dropping the north role: it maps to nothing afterwards.
USE ROLE RAP_KEYED_ADMIN;       USE SECONDARY ROLES NONE;
CALL RAP_KEYED.GOVERNANCE.SP_OFFBOARD_ACCESS('NORTH', 'RAP_KEYED_NORTH_TEAM', TRUE);
SET OFFBOARD_SINGLE = (SELECT $1 FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SHOW ROLES LIKE 'RAP_KEYED_NORTH_TEAM';
SET NORTH_ROLE_LEFT = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
-- The north rows are still in the table, just visible to no role.
SET NORTH_ROWS_KEPT = (SELECT COUNT(*) FROM RAP_KEYED.SHARED.SERVICE_TICKETS WHERE REGION_CODE = 'NORTH');
